#!/usr/bin/env bash

new_project () {
  cookiecutter https://github.com/cfchase/odh-s2i-project-cookiecutter --checkout simple
}

new_repo () {
    echo "creating new git repository from $1"
    pushd $(pwd)

    if [[ -z "$1" ]]; then
      echo "Missing path arg.  odh new-repo <path>"
      exit
    else
      cd $1 || exit
    fi

    local git_email=$(git config --global user.email)
    if [[ -z "$git_email" ]]; then
      echo Please enter git email:
      read git_email
      git config --global user.email "$git_email"
    fi

    local git_name=$(git config --global user.name)
    if [[ -z "$git_name" ]]; then
      echo Please enter git name:
      read git_name
      git config --global user.name "$git_name"
    fi

    gh auth status || gh auth login

    git init
    git add .
    git commit -m "Initial commit generated by ODH"
    gh repo create
    git push origin master
    popd
}

new_app () {
  echo "deploying OpenShift Application $2"
  pushd $(pwd)
  if [[ -z "$1" ]]; then
    echo "Missing path arg.  odh new-app <path> "
    exit
  else
    cd $1 || exit
  fi
  
  local dirname=${PWD##*/}
  local repo=$(git remote -v | head -n 1 | awk -F ' ' '{print $2}'| sed 's|git@github.com:|https://github.com/|g')
  oc project $2 2> /dev/null || oc new-project $2
  oc new-app "python:3.8-ubi8~$repo" \
    -l "odh.io/generator=odhcli" \
    -l "app.kubernetes.io/component=$dirname" \
    -l "app.kubernetes.io/instance=$dirname" \
    -l "app.kubernetes.io/part-of=$dirname"
  popd
}


case $1 in
  new-project)
    new_project
    ;;

  new-repo)
    new_repo $2
    ;;

  new-app)
    new_app $2 $3
    ;;

  *)
    echo $1
    ;;
esac
